# Python
[tool.black]
line-length = 80
skip-string-normalization = 1
target_version = ["py311"]

[tool.flake8]
max-line-length = 80

[tool.ruff]
line-length = 80
extend-ignore = [
    "ANN002", "ANN003", "ANN101", "ANN102", "D103", "D100", "D101",
    "D203", "D204", "D213", "D215", "D400", "D404", "D406", "D407", "D408",
    "D409", "D413",
]  # "E203", "B001", "W503", "R504"
exclude = [".git", "__pycache__", "venv*", ".cache"]
extend-select = ["E", "F", "ANN", "S", "B", "A", "RET", "D"]

[tool.ruff.flake8-annotations]
mypy-init-return = true

[tool.ruff.per-file-ignores]
"tests/test_" = ["D"]
"*/__init__.py" = ["D104"]
